### ISSUE TITLE
Migration to GitHub is not complete

### ISSUE THREAD

**Issue by Neustradamus** [ncroxon/gnu-efi#1]
Dear gnu-efi team, @ncroxon,

Can you add a "move" box like https://sourceforge.net/projects/handbrake for example.
- https://sourceforge.net/p/gnu-efi/

To disable/delete tabs, go here: https://sourceforge.net/projects/gnu-efi/
To add a new tab, go here: https://sourceforge.net/projects/gnu-efi/
To change informations, go here: https://sourceforge.net/p/gnu-efi/admin/overview
To export, go here: https://sourceforge.net/p/gnu-efi/admin/export

The new place can be added in:
- "Moved Project to", here: https://sourceforge.net/p/gnu-efi/admin/overview
- A new tab, go here: https://sourceforge.net/projects/gnu-efi/

Thanks in advance.

**Comment by gmbr3** [comment]
It also needs updating from sourceforge again

**Comment by ncroxon** [comment]
I added a 'Move' box on sourceforge.

**Comment by gmbr3** [comment]
3.0.18 tag is missing
