### ISSUE TITLE
Move riscv64 crt0 to objcopy

### ISSUE THREAD

**Issue by gmbr3** [ncroxon/gnu-efi#11]
gnu-efi should move the crt0 for riscv64 to the objcopy type instead of the 'manual symbols' type as we now have efi-app-riscv64.
We should keep the original and rename it and allow detection of what is the default to prevent mix-ups like ARM64. 

Relates to rhboot/shim#641

**Comment by ncroxon** [comment]
Agreed.

**Comment by jmontleon** [comment]
@gmbr3 It looks like this may still be a work in progress, but I wanted to give some feedback that I was able to use it to build rhboot/shim and boot both a VisionFive 2 and a libvirt VM into Fedora 40 using your work along with the linked PR.

**Comment by gmbr3** [comment]
> @gmbr3 It looks like this may still be a work in progress, based on additional commits since I tried, but I wanted to give some feedback that I was able to use it to build rhboot/shim and boot both a VisionFive 2 and a libvirt VM into Fedora 40 using your work along with the linked PR.

Thanks for your positive feedback
Technically WIP until I get everything I want included done but glad the RISCV64 part works
