### ISSUE TITLE
Cant compile on m2 mac

### ISSUE THREAD

**Issue by amanuel2** [ncroxon/gnu-efi#35]
Mac's are arm64, but there is no compilation target for that under lib/*. I tried changing to arm and aarch64 but that for good reason doesn't work.

**Comment by ncroxon** [comment]
https://github.com/ncroxon/gnu-efi/pull/37

**Comment by amanuel2** [comment]
To get this to compile on my end I had to

1. brew install binutils + `export PATH=$PATH:/opt/homebrew/opt/binutils/bin`
2. remove -D from as (due to error: "illegal option -- D")

But after this there still is the issue that there is no arm64 under `lib/` so compilation under that dir will result in the following:
```
...

  CC       ctors.o
  AR       libefi.a
ar: arm64/initplat.o: No such file or directory
ar: arm64/math.o: No such file or directory
ar: arm64/setjmp.o: No such file or directory
make: *** [libefi.a] Error 1
```

**Comment by ncroxon** [comment]
@gmbr3 has been working on this issue.
Thanks for reporting back what you have found.

**Comment by gmbr3** [comment]
Try using:
make ARCH=aa64 CROSS_COMPILE=aarch64-elf- USING_APPLE=1

And make sure that aarch64-elf-gcc is installed

**Comment by amanuel2** [comment]
Oops i totally forgot to install the cross compiler on my end, thanks. Also maybe adding this might help others compile this easier

```bash
if [[ "$(uname -s)" == "Darwin" && "$(uname -m)" == "arm64" ]]; then
  if ! command -v aarch64-elf-gcc &> /dev/null; then
    brew install aarch64-elf-gcc
  fi
  USING_APPLE=1
fi
```

**Comment by gmbr3** [comment]
Will implement something similar to that above in a new commit
