### ISSUE TITLE
aarch64: ld: warning: file has a LOAD segment with RWX permissions

### ISSUE THREAD

**Issue by stormc** [ncroxon/gnu-efi#47]
When linking [EFI Boot Guard](https://github.com/siemens/efibootguard) with GNU ld (GNU Binutils) 2.43.1 on aarch64, `ld` warns that the resulting `.so` file has "a LOAD segment with RWX permissions" and `readelf` confirms this:

```
Program Headers:
  Type           Offset   VirtAddr           PhysAddr           FileSiz  MemSiz   Flg Align
  LOAD           0x010000 0x0000000000000000 0x0000000000000000 0x018178 0x018178 RWE 0x10000
  DYNAMIC        0x021000 0x0000000000011000 0x0000000000011000 0x0000f0 0x0000f0 RW  0x8
  GNU_STACK      0x000000 0x0000000000000000 0x0000000000000000 0x000000 0x000000 RW  0x10

 Section to Segment mapping:
  Segment Sections...
   00     .hash .text .reloc .dynamic .data .rela .rodata .dynsym .dynstr
   01     .dynamic
   02
```

This was introduced by commit [792715e arm64 lds: move 64K gap to reloc](https://github.com/ncroxon/gnu-efi/commit/792715e) which was released with 3.0.18. Reverting this commit results in the following layout without above mentioned error:

```
Program Headers:
  Type           Offset   VirtAddr           PhysAddr           FileSiz  MemSiz   Flg Align
  LOAD           0x010000 0x0000000000000000 0x0000000000000000 0x00800c 0x00800c R E 0x10000
  LOAD           0x020000 0x0000000000010000 0x0000000000010000 0x007178 0x007178 RW  0x10000
  DYNAMIC        0x020000 0x0000000000010000 0x0000000000010000 0x0000f0 0x0000f0 RW  0x8
  GNU_STACK      0x000000 0x0000000000000000 0x0000000000000000 0x000000 0x000000 RW  0x10

 Section to Segment mapping:
  Segment Sections...
   00     .hash .text .reloc
   01     .dynamic .data .rela .rodata .dynsym .dynstr
   02     .dynamic
   03
```

Now, one can ignore this warning via the `ld` flag `--no-warn-rwx-segments`, fix the linker script to not lump together the sections, or work around this downstream using the `ld` options`-zcommon-page-size` / `-zmax-page-size`. For example, this is the very clean layout when using `max-page-size=2048`:

```
Program Headers:
  Type           Offset   VirtAddr           PhysAddr           FileSiz  MemSiz   Flg Align
  LOAD           0x000800 0x0000000000000000 0x0000000000000000 0x0000dc 0x0000dc R   0x800
  LOAD           0x001000 0x0000000000001000 0x0000000000001000 0x006ea0 0x006ea0 R E 0x1000
  LOAD           0x008000 0x0000000000010000 0x0000000000010000 0x00000c 0x00000c R   0x800
  LOAD           0x008800 0x0000000000011000 0x0000000000011000 0x0000f0 0x0000f0 RW  0x800
  LOAD           0x009000 0x0000000000012000 0x0000000000012000 0x002038 0x002038 RW  0x800
  LOAD           0x00b800 0x0000000000015000 0x0000000000015000 0x002360 0x002360 R   0x800
  LOAD           0x00e000 0x0000000000018000 0x0000000000018000 0x000178 0x000178 R   0x800
  DYNAMIC        0x008800 0x0000000000011000 0x0000000000011000 0x0000f0 0x0000f0 RW  0x8
  GNU_STACK      0x000000 0x0000000000000000 0x0000000000000000 0x000000 0x000000 RW  0x10

 Section to Segment mapping:
  Segment Sections...
   00     .hash
   01     .text
   02     .reloc
   03     .dynamic
   04     .data .rela
   05     .rodata .dynsym
   06     .dynstr
   07     .dynamic
   08
```

Going forward, I would prefer fixing the linker script instead of ignoring this warning or applying fixes downstream. Could you explain what the rationale / idea behind the change in [792715e](https://github.com/ncroxon/gnu-efi/commit/792715e) was?

**Comment by gmbr3** [comment]
> Going forward, I would prefer fixing the linker script instead of ignoring this warning or applying fixes downstream. Could you explain what the rationale / idea behind the change in [792715e](https://github.com/ncroxon/gnu-efi/commit/792715e) was?

It's where objcopy declares the data boundary is when you ask it to create an EFI binary using efi-app-aarch64. Logically, ld should know that .reloc is read-only and create the split there (RX to RW) since there is nothing executable after that point

Why is offset 0x10000 that seems a bit weird?

Also common/max pagesize should be set to 4096 since that's what UEFI expects but this should link in 64K mode otherwise there would be an execution fault when it is read by a 64K paged kernel

Could you provide the full `readelf -a` output for both files as a file upload

**Comment by stormc** [comment]
> > Going forward, I would prefer fixing the linker script instead of ignoring this warning or applying fixes downstream. Could you explain what the rationale / idea behind the change in [792715e](https://github.com/ncroxon/gnu-efi/commit/792715e) was?
> 
> It's where objcopy declares the data boundary is when you ask it to create an EFI binary using efi-app-aarch64. Logically, ld should know that .reloc is read-only and create the split there (RX to RW) since there is nothing executable after that point

Right. Maybe we need to give it a hand here with (excessive) alignment or explicit [PHDRS](https://sourceware.org/binutils/docs/ld/PHDRS.html) definitions and assignments?

> Why is offset 0x10000 that seems a bit weird?

`0x10000` is the 64K boundary that it's aligned on with the resulting PE file having
```
Optional/Image header
    [...]
    Entrypoint:                      0x1000
    Address of .text section:        0x1000
    ImageBase:                       0
    Alignment of sections:           0x1000
    Alignment factor:                0x200
```
As you can have 4KB, 16KB, and 64KB page sizes on aarch64, aligning on 64K seems sensible as that'll run on all configurations.

> Also common/max pagesize should be set to 4096 since that's what UEFI expects but this should link in 64K mode otherwise there would be an execution fault when it is read by a 64K paged kernel

Right, UEFI internally deals with 4K pages ([EDK](https://github.com/tianocore/edk2/blob/master/MdePkg/Include/Uefi/UefiBaseType.h#L181-L183), [U-Boot](https://source.denx.de/u-boot/u-boot/-/blob/392ff1449f7d30cc48fd4d17320d05882cd68f2e/include/efi.h#L273)) which must not necessarily resemble the processor's page size.

> Could you provide the full `readelf -a` output for both files as a file upload

Sure, here's the `readelf –all` output from
* [HEAD, i.e., including 792715e](https://gist.github.com/stormc/157072adabd41af636c5217651650876#file-readelf-head-log),
* [HEAD but 792715e reverted](https://gist.github.com/stormc/157072adabd41af636c5217651650876#file-readelf-792715e-reverted-log), and
* [HEAD but with `-zmax-page-size=4096`](https://gist.github.com/stormc/157072adabd41af636c5217651650876#file-readelf-head-max-page-size-4096-log)

**Comment by gmbr3** [comment]
@stormc Can you check it's fixed please?

**Comment by stormc** [comment]
@gmbr3 I just tested it on aarch64 with EFI Boot Guard on U-Boot and EDK2: it builds and runs fine, thank you very much!
