### ISSUE TITLE
Align ReallocatePool() parameters with EDK2

### ISSUE THREAD

**Issue by gmbr3** [ncroxon/gnu-efi#9]
From https://sourceforge.net/p/gnu-efi/feature-requests/6/ by @pbatard 

Created as an issue because gnu-efi should match EDK2

**Comment by ncroxon** [comment]
matching EDK2 is long over due.

**Comment by gmbr3** [comment]
Working copy commit:
https://github.com/gmbr3/gnu-efi/commit/d7e289f41cbd863ebbef6a20fd3a69872dc76d24
